---
layout: cv
title: Reese Bernard's Portfolio
---
# Reese Bernard
Computer Science student, trombone player, fencer, hobbyist game developer.

<div id="webaddress">
<a href="ReeseBernard52@gmail.com">ReeseBernard52@gmail.com</a>
</div>


## Currently

Studying Computer Science at Brigham Young University

### Specialized in

Nothing currently


## Education

`2023 - present`
__Brigham Young University__

`2019 - 2023`
__Georgetown High School__





## Awards

###### 2023
_`Awarded` a cord for accomplishing 4 years of band._
_`Awarded` first chair for trombone in 2023 SCBDA Region Band._
_`Awarded` The National John Phillips Sousa Award for music._
_`Awarded` first chair for trombone for BYUI University Band._
_`Awarded` a cord for competing in 4 years of varsity cross country._


## Occupation

`2022`
__Line Cook__, Tony's Famous Pizza, Georgetown, South Carolina


`2024`
__Line Cook__, Gramma's Pizza, Anderson, Ohio

`2025 - present`
__Waiter__, The Olive Garden, Anderson, Ohio



<!-- ### Footer

Last updated: May 2013 -->